name: Security Scan (OWASP ZAP)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  securityscanjob:   # <-- ID novo, sem underscore/hífen
    name: Security Scan Job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Start application
        run: |
          nohup npm run start >/dev/null 2>&1 &
          for i in {1..60}; do
            if curl -sSf http://localhost:8080/ >/dev/null; then
              echo "App is up"
              break
            fi
            echo "Waiting for app..."
            sleep 2
          done

      - name: Run OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.11.0
        with:
          target: 'http://localhost:8080'
          cmd_options: '-d -r zap-report.html -J zap-report.json'
          allow_issue_writing: false
          fail_on_warning: false

      - name: List generated reports
        run: ls -la

      - name: Parse ZAP JSON and fail on High/Critical
        run: |
          if [ ! -f zap-report.json ]; then
            echo "ZAP JSON report not found"; exit 2;
          fi
          HIGH_COUNT=$(jq '[.sites[].alerts[] | select(.risk=="High")] | length' zap-report.json)
          CRITICAL_COUNT=$(jq '[.sites[].alerts[] | select(.risk=="Critical")] | length' zap-report.json)
          TOTAL_FAIL=$((HIGH_COUNT + CRITICAL_COUNT))
          echo "High: $HIGH_COUNT, Critical: $CRITICAL_COUNT"
          if [ "$TOTAL_FAIL" -gt 0 ]; then
            echo "Failing pipeline due to $TOTAL_FAIL High/Critical alerts."
            exit 1
          else
            echo "No High/Critical alerts found."
          fi

      - name: Upload ZAP reports
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: |
            zap-report.html
            zap-report.json
          if-no-files-found: error
